export const maps: any = {
  q1: [
    '                                                                                                                          ',
    '                                                                                                                          ',
    '                                  K                                                                                       ',
    '                                                                                                                          ',
    '                                                q                                                                          ',
    '                                                                                                                          ',
    '                                                                                                                          ',
    '                                                                                                                          ',
    '            q                                                                                                              ',
    '                                                                                                                          ',
    '                             -                                                                                            ',
    '                                                                                                                          ',
    '                                     1       2                                                                            ',
    '                                                                                                                          ',
    '                                                                                                                          ',
    '                                      ~_      +"                                                                          ',
    '                                      []      []                                                                          ',
    'ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
  ],
  q2: [
    '                                                                                                                                                                                  ',
    '                                                                                                                                                                                  ',
    '                                                                                                                                                                                  ',
    '                                                                                                                                                                                  ',
    '                                                                                                                                                                                  ',
    '                                                                                                            K                                                                     ',
    '                                                                                                                                                                                  ',
    '                                                                            q                                                           K                                         ',
    '                                                                                                                             q                                                    ',
    '                                  K      d                                                                                                            K                           ',
    '                                                                                                  @                                                                               ',
    '                                         o                                                                                                                                        ',
    '                                                                                                                    /        \\        |        !       )                         ',
    '                                         e                                   :  ;:                                                                                                ',
    '                                                                                                                                                                                  ',
    '                                         l                                                                          ~_       +"       `0       {}      mb                         ',
    '                                                                                       v      v                     []       []       []       []      []                         ',
    'cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
  ],
  q3: [
    '                                                                                                                                                                  ',
    '                                                                                                          K                                                       ',
    '                                                                                                                $                                                 ',
    '                                                                                                                $    =====                                        ',
    '                                                                                                                $          w       +"                             ',
    '                                                                                         K                      $                  []     q                       ',
    '                                q                                                                               $                ======                           ',
    '                                                                                                                $        $                                        ',
    '                                                              q                                     a           $        $  ===                                   ',
    '                                                                                                                $        $                ===                     ',
    '                                                              #                               ==    $$          $        $                                        ',
    '                                                                                        $$$   ==    $$          $        $                                        ',
    '                                                           $                            ===         ~_          $$       $           ===                          ',
    '                                                         $ =                            ===         []          $$       $                                        ',
    '                                                       $ = =                         =             ====         $$       $                                        ',
    '                                                     $ = = =                       = =            ======        $$       $       ===                              ',
    '                                              $$$$   = = = =                     = = =  $$$$$$$$$========       $$       $                                        ',
    'cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
  ],
  q41: [
    '                                                                                                                                                ',
    '                                                                                                                                                ',
    '                                                                                                                                                ',
    '                                                                                                                                                ',
    '                          K                                                                                                                     ',
    '                                                                                                                                                ',
    '                                                                                   q                                                            ',
    '                                                                                                                                                ',
    '                                                                                                                                                ',
    '                                                              =                                                                                 ',
    '                                                              =        ;    >y      <x                                                          ',
    '                                                             4=                                                                                 ',
    '                                                            4==                                                                                 ',
    '                                                           4===                                                                                 ',
    '                                                          =====4444  444================                                                        ',
    '                                                         ==========  $$$$$$$$$$$$$$$$$$$               ~_                                       ',
    '                                            $$$$$$$$$$$$=========== v$$$$$$$$$$$$$$$$$$$    v          []                                       ',
    'ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc88cccccccccccccccccccccccccccccccccccccccjjjjjjjjjjjjccccccccccccccccccccccccccccccccccccccccccccc',
  ],
  q42: [
    '                                                                                                                                           ',
    '                                                                                                                                           ',
    '                                                                                                                                           ',
    '                                                                                                                                           ',
    '                                                              K                                                                            ',
    '                                                                                                                                           ',
    '                                      K                                                                                                    ',
    '                                                                                         q                                                 ',
    '                                                                          ~_                                                               ',
    '                                                                          []                                                               ',
    '                                                kkkkkkkk   =====nnnnnnnnnn==nn                                                             ',
    '                                               k=                            ==                                                            ',
    '                                              k==                            ===                                                           ',
    '                                             k===            gy     hx    ;: ====                                                          ',
    '                                            =====       kk                   =====                                                         ',
    '                                           ======$    $   $                  ======                                                        ',
    '                                          =======$    $   $                  =======                                                       ',
    'cccccccccccccccccccccccccjjjjjjjjjjjjccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
  ],
  q43: [
    '                                                                                                                  ',
    '                                                                      K                                           ',
    '                                                                                       $                          ',
    '                                                                            $$$$$$$$   $                          ',
    '                                                                            ========   $                          ',
    '                                                                                       $     K                    ',
    '                                                                $$$$$$$$$$             $                          ',
    '                                                      q         ==========             $                          ',
    '                                                                                       $                $$$       ',
    '                        K                                                              $              zzzzzzz     ',
    '                                                           ===                         $                       q  ',
    '                                                                                       $                          ',
    '                                                     ppp                               $         zzz              ',
    '                                                                           5y     6x   $                          ',
    '                                               ppp                                     $                          ',
    '                                                                                       $   zzz           ~_       ',
    '                                                            $$$$$$$$$$$$$$$$$$$        $                 []       ',
    'ccccccccccccccccccccccccccccccccccccccccccccccc7777777777cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
  ],
  q5: [
    '                                                                                                 ',
    '                                       K                                                         ',
    '                  q                                                       K                      ',
    '                                                                                                 ',
    '                                                                                                 ',
    '                                         &                    q                                  ',
    '                                                                                                 ',
    '                                                                                                 ',
    '                                                                                                 ',
    'cccccccccccccccccccccccccc================================================    ====cccccccccccccccccccccccccccccccccccccccccccccccccc',
    '                          =                                                      =',
    '                          =                r       f       s                     =',
    '                          =                                                      =',
    '                          =                                                      =',
    '                          =                                                      =',
    '                          =                 ~_      +"      `0                   =',
    '                          =                 []      []      []                   =',
    '                          ========================================================',
  ]
};
